### ISSUE TITLE
DataLad works on McOS and Windows (albeit harder to install) no only linux

### ISSUE THREAD

**Issue by jbpoline** [CONP-PCNO/conp-documentation#22]
Should be a quick fix - also add link to install there

**Comment by cmadjar** [comment]
This information is present in the following document linked in the FAQ: 
- https://github.com/CONP-PCNO/conp-documentation/blob/master/datalad_dataset_addition_procedure.md#install-on-a-linux-machines-with-no-root-access-eg-hpc-systems

Note that in the DataLad link of the CONP dataset pages, the link redirect the user to the DataLad handbook install page where information about install is available for Linux, Mac OS X and Windows.

@jbpoline Does that seem reasonable to you?

**Comment by cmadjar** [comment]
This has been resolved by updating links to the DataLad handbook and adding information in the FAQ.
