### ISSUE TITLE
In the FAQ, add instructions on how to create a DATS model

### ISSUE THREAD

**Issue by glatard** [CONP-PCNO/conp-documentation#31]
This should also be mentioned in data upload to Zenodo or OSF: if users add a DATS model at the root of the dataset, it will be used instead of the default one created by the crawler.

**Comment by cmadjar** [comment]
@emmetaobrien Is that something you could add to the FAQ documentation? Thanks!

**Comment by emmetaobrien** [comment]
There is a start on this is in section 2 of https://github.com/CONP-PCNO/conp-documentation/blob/master/CONP_main_data_documentation.htm - suggestions as to how to make that more useful/user-friendly definitely welcome.

**Comment by cmadjar** [comment]
Is there a reason why https://github.com/CONP-PCNO/conp-documentation/blob/master/CONP_main_data_documentation.htm is in html? Could we convert it to MD like all the other documentation?

That file seems a little outdated. The title is "Uploading data for CONP" but that is not really the content of the file as far as I can tell. 

There is also that file: [CONP_DATS_fields.md](https://github.com/CONP-PCNO/conp-documentation/blob/master/CONP_DATS_fields.md).

Maybe we could update the [CONP_DATS_fields.md](https://github.com/CONP-PCNO/conp-documentation/blob/master/CONP_DATS_fields.md) file to add some context?

For example:

> We use the `DATS.json` file format to store metadata describing CONP datasets. `DATS.json` is a flexible machine-readable structure allowing for sophisticated representation of a wide range of different types of datasets, from neuroimaging to genomics. A `DATS.json` file must be prepared for each dataset. Below is a table summarizing the list of required, recommended and optional fields.

then show the table

> The DATS dataset schema can be found [here](https://github.com/CONP-PCNO/schema/blob/master/dataset_schema.json). The example `DATS.json` file for the 1000 Genomes Project [here](https://github.com/conpdatasets/1000GenomesProject/blob/master/DATS.json) can be used as a template. An interface allowing users to fill in required fields online is under development [here](https://dats-creator.herokuapp.com/).


Then, in the FAQ question, we could answer with the link to the CONP_DATS_fields.md file.

This way, we only have to update one document any time there is a change.

@glatard @emmetaobrien what do you guys think?

**Comment by emmetaobrien** [comment]
That all sounds good to me; CONP_main_data_documentation.htm is indeed out of date, and I think CONP_DATS_fields.md makes sense as a single place to centralise this information.  We might want to pick a different DATS.json to suggest as template at this point, though; the 1000 Genomes Project is one of the datasets where the `creators` entry is an organisation, and if we use one where that entry is a person or list of people it would also serve as an example of how we are identifying the PI with an annotation in DATS.json as per https://github.com/CONP-PCNO/conp-portal/issues/254.

**Comment by cmadjar** [comment]
Totally agree with you. Let's pick a more recent DATS.json file as an example. I'll let you decide which one is the most relevant as you are more versed in that area than me.

Thank you :)

**Comment by emmetaobrien** [comment]
I suggest the visual-working-memory DATS.json at https://github.com/emmetaobrien/ds001634/blob/master/DATS.json.
