### ISSUE TITLE
Redundant documentation

### ISSUE THREAD

**Issue by glatard** [CONP-PCNO/conp-documentation#7]
The two files below have quite a bit of overlap, they should be merged:

* https://github.com/CONP-PCNO/conp-documentation/blob/master/datalad_dataset_addition_procedure.md

* https://github.com/CONP-PCNO/conp-dataset/blob/master/.github/CONTRIBUTING.md

**Comment by cmadjar** [comment]
@glatard Should we delete the file on conp-dataset repo (after ensuring that all the information it contains is present in the other MD file that is present in the conp-documentation repo)?
