### ISSUE TITLE
add explanation on how to use the DATS dataset fields

### ISSUE THREAD

**Issue by surchs** [CONP-PCNO/conp-documentation#75]
The [DATS dataset schema](https://github.com/CONP-PCNO/schema/blob/master/dataset_schema.json) has several fields that could all be considered to be a place where concept level annotation could be stored (e.g. `types`, `isAbout`, `keywords`). It would be good to explain to users how we would like them to use these fields.

## `types`
> A term, ideally from a controlled terminology, identifying the dataset type or nature of the data, placing it in a typology

We want to use it to describe the modality or dataset type (e.g. "MRI")

## `keywords`
> Tags associated with the dataset, which will help in its discovery.

We use it for: simple keyword tags (not necessarily URIs) to help with search

## `isAbout`
> Different entities (biological entity, taxonomic information, disease, molecular entity, anatomical part, treatment) associated with this dataset.

We want to use it for: more complex, concept level annotations that describe what the dataset is about. For example ("Homo Sapiens" together with a URI that dereferences to a controlled vocabulary).

This documentation could also be something that is only implemented for the dats-editor itself.

**Comment by cmadjar** [comment]
@surchs Am I wrong in thinking this should be closed? Let me know. Thanks!

**Comment by surchs** [comment]
Yes @cmadjar, I agree this is taken care of by the changes to the docs / DATS editor
